/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                        invitationCode: string;
                    };
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                username: string;
                            };
                        };
                    };
                };
                /** @description Invalid registration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Username already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Registration failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    state: ("watching" | "plan_to_watch" | "completed" | "dropped") | "all";
                    sort: "updated" | "added" | "alphabetical";
                    order: "newest" | "oldest";
                    language: "all" | "sub" | "dub";
                    media: "all" | "series" | "movie";
                    type: "all" | "airing" | "finished" | "not_yet_released" | "cancelled" | "hiatus";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: {
                                id: number;
                                href: string;
                                link: string;
                                title: string;
                                image: string;
                                audioLabel: string;
                                format?: string | null;
                                status?: string | null;
                                score: number;
                                genres: string[];
                                synopsis: string;
                                /** @enum {string} */
                                state: "watching" | "plan_to_watch" | "completed" | "dropped";
                            }[];
                            totalEntries: number;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Operation failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist states */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: {
                                animeId: number;
                                /** @enum {string} */
                                state: "watching" | "plan_to_watch" | "completed" | "dropped";
                            }[];
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist/{anilistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    anilistId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            animeId: number;
                            /** @enum {string|null} */
                            state: "watching" | "plan_to_watch" | "completed" | "dropped" | null;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    anilistId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        state: "watching" | "plan_to_watch" | "completed" | "dropped";
                    };
                };
            };
            responses: {
                /** @description Updated watchlist state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            animeId: number;
                            /** @enum {string|null} */
                            state: "watching" | "plan_to_watch" | "completed" | "dropped" | null;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    anilistId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist entry removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
                /** @description Operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "AUTHENTICATION_REQUIRED" | "INTERNAL_ERROR" | "INVALID_REQUEST" | "INVITATION_COMPLETION_FAILED" | "INVITATION_INVALID" | "NOT_FOUND" | "ORIGIN_FORBIDDEN" | "REGISTRATION_FAILED" | "USERNAME_TAKEN" | "WATCHLIST_LOAD_FAILED" | "WATCHLIST_REMOVE_FAILED" | "WATCHLIST_UPDATE_FAILED";
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
