version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - errcheck
    - funlen
    - gocognit
    - gocyclo
    - govet
    - ineffassign
    - maintidx
    - nakedret
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: early-return
        - name: error-naming
        - name: error-return
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unnecessary-stmt
        - name: var-declaration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
