version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - maintidx
    - makezero
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    gocritic:
      disable-all: true
      enabled-checks:
        - appendCombine
        - boolExprSimplify
        - commentedOutCode
        - commentedOutImport
        - deferUnlambda
        - dupBranchBody
        - dupImport
        - dupSubExpr
        - emptyDecl
        - emptyFallthrough
        - emptyStringTest
        - equalFold
        - redundantSprint
        - regexpPattern
        - stringConcatSimplify
        - typeUnparen
        - underef
        - unlambda
        - unnecessaryBlock
        - unnecessaryDefer
        - unslice
    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: early-return
        - name: error-naming
        - name: error-return
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unnecessary-stmt
        - name: var-declaration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules/

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
