// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Anime struct {
	ID                int64           `json:"id"`
	TitleOriginal     string          `json:"title_original"`
	TitleEnglish      sql.NullString  `json:"title_english"`
	TitleJapanese     sql.NullString  `json:"title_japanese"`
	ImageUrl          string          `json:"image_url"`
	BannerImageUrl    string          `json:"banner_image_url"`
	CreatedAt         time.Time       `json:"created_at"`
	Airing            sql.NullBool    `json:"airing"`
	Status            sql.NullString  `json:"status"`
	RelationsSyncedAt sql.NullTime    `json:"relations_synced_at"`
	DurationSeconds   sql.NullFloat64 `json:"duration_seconds"`
}

type AnimeEffectiveMapping struct {
	AnilistID     int64         `json:"anilist_id"`
	MalID         sql.NullInt64 `json:"mal_id"`
	TmdbMediaType string        `json:"tmdb_media_type"`
	TmdbID        int64         `json:"tmdb_id"`
	TmdbSeason    int32         `json:"tmdb_season"`
	Canonical     bool          `json:"canonical"`
}

type AnimeExternalMapping struct {
	AnilistID     int64         `json:"anilist_id"`
	MalID         sql.NullInt64 `json:"mal_id"`
	TmdbMediaType string        `json:"tmdb_media_type"`
	TmdbID        int64         `json:"tmdb_id"`
	TmdbSeason    int32         `json:"tmdb_season"`
	Source        string        `json:"source"`
	ImportedAt    time.Time     `json:"imported_at"`
}

type AnimeInferredMapping struct {
	AnilistID        int64         `json:"anilist_id"`
	MalID            sql.NullInt64 `json:"mal_id"`
	TmdbMediaType    string        `json:"tmdb_media_type"`
	TmdbID           int64         `json:"tmdb_id"`
	TmdbSeason       int32         `json:"tmdb_season"`
	RelationType     string        `json:"relation_type"`
	RelatedAnilistID int64         `json:"related_anilist_id"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type AnimeMappingImport struct {
	Singleton     bool      `json:"singleton"`
	Source        string    `json:"source"`
	SchemaVersion string    `json:"schema_version"`
	Etag          string    `json:"etag"`
	EntryCount    int64     `json:"entry_count"`
	ImportedAt    time.Time `json:"imported_at"`
}

type AnimeMappingOverride struct {
	AnilistID     int64          `json:"anilist_id"`
	MalID         sql.NullInt64  `json:"mal_id"`
	TmdbMediaType sql.NullString `json:"tmdb_media_type"`
	TmdbID        sql.NullInt64  `json:"tmdb_id"`
	TmdbSeason    int32          `json:"tmdb_season"`
	Canonical     bool           `json:"canonical"`
	Excluded      bool           `json:"excluded"`
	Note          string         `json:"note"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type ApiToken struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	TokenHash  string       `json:"token_hash"`
	Name       string       `json:"name"`
	CreatedAt  time.Time    `json:"created_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type ContinueWatchingEntry struct {
	ID                 string          `json:"id"`
	UserID             string          `json:"user_id"`
	AnimeID            int64           `json:"anime_id"`
	CurrentEpisode     sql.NullInt64   `json:"current_episode"`
	CurrentTimeSeconds float64         `json:"current_time_seconds"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	DurationSeconds    sql.NullFloat64 `json:"duration_seconds"`
}

type DataFix struct {
	ID        string    `json:"id"`
	AppliedAt time.Time `json:"applied_at"`
}

type GeneratedSubtitle struct {
	AnimeID   int64     `json:"anime_id"`
	Episode   int64     `json:"episode"`
	Mode      string    `json:"mode"`
	Model     string    `json:"model"`
	Status    string    `json:"status"`
	Vtt       string    `json:"vtt"`
	Error     string    `json:"error"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NotificationPreference struct {
	UserID  string `json:"user_id"`
	Enabled bool   `json:"enabled"`
}

type RecommendationEvent struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	AnimeID      sql.NullInt64  `json:"anime_id"`
	EventType    string         `json:"event_type"`
	Source       sql.NullString `json:"source"`
	MetadataJson sql.NullString `json:"metadata_json"`
	OccurredAt   time.Time      `json:"occurred_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type RecommendationImpression struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	AnimeID      int64          `json:"anime_id"`
	Rail         string         `json:"rail"`
	Position     int64          `json:"position"`
	RequestID    sql.NullString `json:"request_id"`
	MetadataJson sql.NullString `json:"metadata_json"`
	OccurredAt   time.Time      `json:"occurred_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type RecommendationProfileSnapshot struct {
	UserID            string       `json:"user_id"`
	ProfileJson       string       `json:"profile_json"`
	SourceWindowStart sql.NullTime `json:"source_window_start"`
	SourceWindowEnd   sql.NullTime `json:"source_window_end"`
	ComputedAt        time.Time    `json:"computed_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SkipSegmentOverride struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	AnimeID   int64     `json:"anime_id"`
	Episode   int64     `json:"episode"`
	SkipType  string    `json:"skip_type"`
	StartTime float64   `json:"start_time"`
	EndTime   float64   `json:"end_time"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	AvatarUrl    string    `json:"avatar_url"`
}

type WatchListEntry struct {
	ID                   string        `json:"id"`
	UserID               string        `json:"user_id"`
	AnimeID              int64         `json:"anime_id"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	CurrentEpisode       sql.NullInt64 `json:"current_episode"`
	LastEpisodeAt        sql.NullTime  `json:"last_episode_at"`
	CurrentTimeSeconds   float64       `json:"current_time_seconds"`
	CompletedAt          sql.NullTime  `json:"completed_at"`
	CompletedAtEstimated bool          `json:"completed_at_estimated"`
}
