// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteContinueWatchingEntry(ctx context.Context, arg DeleteContinueWatchingEntryParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteWatchListEntry(ctx context.Context, arg DeleteWatchListEntryParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAnime(ctx context.Context, id int64) (Anime, error)
	GetAuditLogsForUser(ctx context.Context, arg GetAuditLogsForUserParams) ([]AuditLog, error)
	GetContinueWatchingCarouselEntries(ctx context.Context, arg GetContinueWatchingCarouselEntriesParams) ([]GetContinueWatchingCarouselEntriesRow, error)
	GetContinueWatchingEntries(ctx context.Context, userID string) ([]GetContinueWatchingEntriesRow, error)
	GetContinueWatchingEntry(ctx context.Context, arg GetContinueWatchingEntryParams) (ContinueWatchingEntry, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTrackedAiringAnimeIDs(ctx context.Context, limit int32) ([]int64, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserWatchList(ctx context.Context, userID string) ([]GetUserWatchListRow, error)
	GetWatchListEntry(ctx context.Context, arg GetWatchListEntryParams) (WatchListEntry, error)
	GetWatchingAnime(ctx context.Context, userID string) ([]GetWatchingAnimeRow, error)
	RefreshSession(ctx context.Context, arg RefreshSessionParams) error
	RevokeAllAPITokensForUser(ctx context.Context, userID string) error
	SaveWatchProgress(ctx context.Context, arg SaveWatchProgressParams) error
	TouchAPITokenLastUsedAt(ctx context.Context, id string) error
	UpsertAnime(ctx context.Context, arg UpsertAnimeParams) (Anime, error)
	UpsertContinueWatchingEntry(ctx context.Context, arg UpsertContinueWatchingEntryParams) (ContinueWatchingEntry, error)
	UpsertWatchListEntry(ctx context.Context, arg UpsertWatchListEntryParams) (WatchListEntry, error)
}

var _ Querier = (*Queries)(nil)
