query AllAnimeSearch($search: SearchInput, $translationType: VaildTranslationTypeEnumType) {
    shows(
        search: $search
        limit: 40
        page: 1
        translationType: $translationType
        countryOrigin: ALL
    ) {
        edges {
            _id
            malId
            name
        }
    }
}

query AllAnimeAvailableEpisodes($showId: String!, $start: Float!, $end: Float!) {
    show(_id: $showId) {
        availableEpisodesDetail
    }
    episodeInfos(showId: $showId, episodeNumStart: $start, episodeNumEnd: $end) {
        episodeIdNum
        notes
    }
}

query AllAnimeWeeklyPopular {
    queryPopular(
        type: anime
        size: 100
        dateRange: 7
        page: 1
        allowAdult: false
        allowUnknown: false
        denyEcchi: true
    ) {
        recommendations {
            anyCard {
                aniListId
                availableEpisodesDetail
                siteRanks {
                    weekly {
                        position
                    }
                }
            }
        }
    }
}

query AllAnimeSimulcastPage($search: SearchInput, $page: Int!, $limit: Int!) {
    shows(search: $search, limit: $limit, page: $page, countryOrigin: ALL) {
        edges {
            _id
            aniListId
            name
            englishName
            description
            thumbnail
            averageScore
            genres
            season
            availableEpisodesDetail
        }
    }
}

query AllAnimeEpisodeSources(
    $showId: String!
    $translationType: VaildTranslationTypeEnumType!
    $episodeString: String!
) {
    episode(showId: $showId, translationType: $translationType, episodeString: $episodeString) {
        sourceUrls
    }
}

query AllAnimeExpandedEpisodeSources(
    $showId: String!
    $translationType: VaildTranslationTypeEnumType!
    $episodeString: String!
) {
    episode(showId: $showId, translationType: $translationType, episodeString: $episodeString) {
        episodeString
        uploadDate
        sourceUrls
        thumbnail
        notes
        show {
            _id
            name
            englishName
            nativeName
            slugTime
            thumbnail
            tbObj {
                u
                sm
                md
                ts
            }
            lastEpisodeInfo
            lastEpisodeDate
            type
            season
            score
            airedStart
            availableEpisodes
            episodeDuration
            episodeCount
            lastUpdateEnd
            characterCount
            description
            broadcastInterval
            banner
            characters
            availableEpisodesDetail
            nameOnlyString
            characters
            isAdult
            relatedShows
            relatedMangas
            altNames
            disqusIds
        }
        pageStatus {
            _id
            notes
            pageId
            showId
            views
            likesCount
            commentCount
            dislikesCount
            boostsCount
            reviewCount
            userScoreCount
            userScoreTotalValue
            userScoreAverValue
            viewers {
                firstViewers {
                    viewCount
                    lastWatchedDate
                    user {
                        _id
                        username
                        displayName
                        createdAt
                        picture
                        reputation
                        roleLevel
                        brief
                        followerCount
                        followingCount
                        pDec
                        equippedBadgeKey
                        equippedBadge {
                            key
                            name
                            rank
                            iconPath
                            date
                        }
                        ugcContributorStats {
                            mediaEditReviewSubmitCount
                            mediaEditApprovedCount
                            mediaEditRejectedCount
                            mediaEditAppliedCount
                            mediaEditContributionPoints
                            mediaEditModContributionPoints
                        }
                        hideMe
                    }
                }
                recViewers {
                    viewCount
                    lastWatchedDate
                    user {
                        _id
                        username
                        displayName
                        createdAt
                        picture
                        reputation
                        roleLevel
                        brief
                        followerCount
                        followingCount
                        pDec
                        equippedBadgeKey
                        equippedBadge {
                            key
                            name
                            rank
                            iconPath
                            date
                        }
                        ugcContributorStats {
                            mediaEditReviewSubmitCount
                            mediaEditApprovedCount
                            mediaEditRejectedCount
                            mediaEditAppliedCount
                            mediaEditContributionPoints
                            mediaEditModContributionPoints
                        }
                        hideMe
                    }
                }
            }
        }
        episodeInfo {
            notes
            thumbnails
            tbObj {
                u
                sm
                md
                ts
            }
            vidInforssub
            uploadDates
            vidInforsdub
            vidInforsraw
            description
        }
        versionFix
    }
}
