query AllAnimeSearch($search: SearchInput, $translationType: VaildTranslationTypeEnumType) {
  shows(
    search: $search
    limit: 40
    page: 1
    translationType: $translationType
    countryOrigin: ALL
  ) {
    edges {
      _id
      malId
      name
    }
  }
}

query AllAnimeAvailableEpisodes($showId: String!, $start: Float!, $end: Float!) {
  show(_id: $showId) {
    availableEpisodesDetail
  }
  episodeInfos(showId: $showId, episodeNumStart: $start, episodeNumEnd: $end) {
    episodeIdNum
    notes
  }
}

query AllAnimeWeeklyPopular {
  queryPopular(
    type: anime
    size: 100
    dateRange: 7
    page: 1
    allowAdult: false
    allowUnknown: false
    denyEcchi: true
  ) {
    recommendations {
      anyCard {
        aniListId
        availableEpisodesDetail
        siteRanks {
          weekly {
            position
          }
        }
      }
    }
  }
}

query AllAnimeSimulcastPage($search: SearchInput, $page: Int!, $limit: Int!) {
  shows(search: $search, limit: $limit, page: $page, countryOrigin: ALL) {
    edges {
      _id
      aniListId
      name
      englishName
      description
      thumbnail
      averageScore
      genres
      season
      availableEpisodesDetail
    }
  }
}

query AllAnimeEpisodeSources(
  $showId: String!
  $translationType: VaildTranslationTypeEnumType!
  $episodeString: String!
) {
  episode(showId: $showId, translationType: $translationType, episodeString: $episodeString) {
    sourceUrls
  }
}
