// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package allanime

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

// AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo includes the requested fields of the GraphQL type EpisodeInfo.
type AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo struct {
	EpisodeIdNum FlexibleInt `json:"episodeIdNum"`
	Notes        string      `json:"notes"`
}

// GetEpisodeIdNum returns AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo.EpisodeIdNum, and is useful for accessing the field via an interface.
func (v *AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo) GetEpisodeIdNum() FlexibleInt {
	return v.EpisodeIdNum
}

// GetNotes returns AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo.Notes, and is useful for accessing the field via an interface.
func (v *AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo) GetNotes() string { return v.Notes }

// AllAnimeAvailableEpisodesResponse is returned by AllAnimeAvailableEpisodes on success.
type AllAnimeAvailableEpisodesResponse struct {
	Show         *AllAnimeAvailableEpisodesShow                     `json:"show"`
	EpisodeInfos []AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo `json:"episodeInfos"`
}

// GetShow returns AllAnimeAvailableEpisodesResponse.Show, and is useful for accessing the field via an interface.
func (v *AllAnimeAvailableEpisodesResponse) GetShow() *AllAnimeAvailableEpisodesShow { return v.Show }

// GetEpisodeInfos returns AllAnimeAvailableEpisodesResponse.EpisodeInfos, and is useful for accessing the field via an interface.
func (v *AllAnimeAvailableEpisodesResponse) GetEpisodeInfos() []AllAnimeAvailableEpisodesEpisodeInfosEpisodeInfo {
	return v.EpisodeInfos
}

// AllAnimeAvailableEpisodesShow includes the requested fields of the GraphQL type Show.
type AllAnimeAvailableEpisodesShow struct {
	AvailableEpisodesDetail Object `json:"availableEpisodesDetail"`
}

// GetAvailableEpisodesDetail returns AllAnimeAvailableEpisodesShow.AvailableEpisodesDetail, and is useful for accessing the field via an interface.
func (v *AllAnimeAvailableEpisodesShow) GetAvailableEpisodesDetail() Object {
	return v.AvailableEpisodesDetail
}

// AllAnimeDirectSequelsResponse is returned by AllAnimeDirectSequels on success.
type AllAnimeDirectSequelsResponse struct {
	Show *AllAnimeDirectSequelsShow `json:"show"`
}

// GetShow returns AllAnimeDirectSequelsResponse.Show, and is useful for accessing the field via an interface.
func (v *AllAnimeDirectSequelsResponse) GetShow() *AllAnimeDirectSequelsShow { return v.Show }

// AllAnimeDirectSequelsShow includes the requested fields of the GraphQL type Show.
type AllAnimeDirectSequelsShow struct {
	RelatedShows []AllAnimeDirectSequelsShowRelatedShowsRelatedShow `json:"relatedShows"`
}

// GetRelatedShows returns AllAnimeDirectSequelsShow.RelatedShows, and is useful for accessing the field via an interface.
func (v *AllAnimeDirectSequelsShow) GetRelatedShows() []AllAnimeDirectSequelsShowRelatedShowsRelatedShow {
	return v.RelatedShows
}

// AllAnimeDirectSequelsShowRelatedShowsRelatedShow includes the requested fields of the GraphQL type RelatedShow.
type AllAnimeDirectSequelsShowRelatedShowsRelatedShow struct {
	Relation string `json:"relation"`
	ShowId   string `json:"showId"`
}

// GetRelation returns AllAnimeDirectSequelsShowRelatedShowsRelatedShow.Relation, and is useful for accessing the field via an interface.
func (v *AllAnimeDirectSequelsShowRelatedShowsRelatedShow) GetRelation() string { return v.Relation }

// GetShowId returns AllAnimeDirectSequelsShowRelatedShowsRelatedShow.ShowId, and is useful for accessing the field via an interface.
func (v *AllAnimeDirectSequelsShowRelatedShowsRelatedShow) GetShowId() string { return v.ShowId }

// AllAnimeEpisodeSourcesEpisode includes the requested fields of the GraphQL type Episode.
type AllAnimeEpisodeSourcesEpisode struct {
	SourceUrls Object `json:"sourceUrls"`
}

// GetSourceUrls returns AllAnimeEpisodeSourcesEpisode.SourceUrls, and is useful for accessing the field via an interface.
func (v *AllAnimeEpisodeSourcesEpisode) GetSourceUrls() Object { return v.SourceUrls }

// AllAnimeEpisodeSourcesResponse is returned by AllAnimeEpisodeSources on success.
type AllAnimeEpisodeSourcesResponse struct {
	Episode *AllAnimeEpisodeSourcesEpisode `json:"episode"`
}

// GetEpisode returns AllAnimeEpisodeSourcesResponse.Episode, and is useful for accessing the field via an interface.
func (v *AllAnimeEpisodeSourcesResponse) GetEpisode() *AllAnimeEpisodeSourcesEpisode {
	return v.Episode
}

// AllAnimeProviderShowResponse is returned by AllAnimeProviderShow on success.
type AllAnimeProviderShowResponse struct {
	Show *AllAnimeProviderShowShow `json:"show"`
}

// GetShow returns AllAnimeProviderShowResponse.Show, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowResponse) GetShow() *AllAnimeProviderShowShow { return v.Show }

// AllAnimeProviderShowShow includes the requested fields of the GraphQL type Show.
type AllAnimeProviderShowShow struct {
	ProviderShowFields `json:"-"`
}

// GetId returns AllAnimeProviderShowShow.Id, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetId() string { return v.ProviderShowFields.Id }

// GetName returns AllAnimeProviderShowShow.Name, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetName() string { return v.ProviderShowFields.Name }

// GetEnglishName returns AllAnimeProviderShowShow.EnglishName, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetEnglishName() string { return v.ProviderShowFields.EnglishName }

// GetDescription returns AllAnimeProviderShowShow.Description, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetDescription() string { return v.ProviderShowFields.Description }

// GetMalId returns AllAnimeProviderShowShow.MalId, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetMalId() string { return v.ProviderShowFields.MalId }

// GetStatus returns AllAnimeProviderShowShow.Status, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetStatus() string { return v.ProviderShowFields.Status }

// GetThumbnail returns AllAnimeProviderShowShow.Thumbnail, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetThumbnail() string { return v.ProviderShowFields.Thumbnail }

// GetType returns AllAnimeProviderShowShow.Type, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetType() string { return v.ProviderShowFields.Type }

// GetSeason returns AllAnimeProviderShowShow.Season, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetSeason() Object { return v.ProviderShowFields.Season }

// GetEpisodeCount returns AllAnimeProviderShowShow.EpisodeCount, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetEpisodeCount() string { return v.ProviderShowFields.EpisodeCount }

// GetAvailableEpisodesDetail returns AllAnimeProviderShowShow.AvailableEpisodesDetail, and is useful for accessing the field via an interface.
func (v *AllAnimeProviderShowShow) GetAvailableEpisodesDetail() Object {
	return v.ProviderShowFields.AvailableEpisodesDetail
}

func (v *AllAnimeProviderShowShow) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*AllAnimeProviderShowShow
		graphql.NoUnmarshalJSON
	}
	firstPass.AllAnimeProviderShowShow = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ProviderShowFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalAllAnimeProviderShowShow struct {
	Id string `json:"_id"`

	Name string `json:"name"`

	EnglishName string `json:"englishName"`

	Description string `json:"description"`

	MalId string `json:"malId"`

	Status string `json:"status"`

	Thumbnail string `json:"thumbnail"`

	Type string `json:"type"`

	Season Object `json:"season"`

	EpisodeCount string `json:"episodeCount"`

	AvailableEpisodesDetail Object `json:"availableEpisodesDetail"`
}

func (v *AllAnimeProviderShowShow) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *AllAnimeProviderShowShow) __premarshalJSON() (*__premarshalAllAnimeProviderShowShow, error) {
	var retval __premarshalAllAnimeProviderShowShow

	retval.Id = v.ProviderShowFields.Id
	retval.Name = v.ProviderShowFields.Name
	retval.EnglishName = v.ProviderShowFields.EnglishName
	retval.Description = v.ProviderShowFields.Description
	retval.MalId = v.ProviderShowFields.MalId
	retval.Status = v.ProviderShowFields.Status
	retval.Thumbnail = v.ProviderShowFields.Thumbnail
	retval.Type = v.ProviderShowFields.Type
	retval.Season = v.ProviderShowFields.Season
	retval.EpisodeCount = v.ProviderShowFields.EpisodeCount
	retval.AvailableEpisodesDetail = v.ProviderShowFields.AvailableEpisodesDetail
	return &retval, nil
}

// AllAnimeSearchResponse is returned by AllAnimeSearch on success.
type AllAnimeSearchResponse struct {
	Shows AllAnimeSearchShowsShowConnection `json:"shows"`
}

// GetShows returns AllAnimeSearchResponse.Shows, and is useful for accessing the field via an interface.
func (v *AllAnimeSearchResponse) GetShows() AllAnimeSearchShowsShowConnection { return v.Shows }

// AllAnimeSearchShowsShowConnection includes the requested fields of the GraphQL type ShowConnection.
type AllAnimeSearchShowsShowConnection struct {
	Edges []AllAnimeSearchShowsShowConnectionEdgesShow `json:"edges"`
}

// GetEdges returns AllAnimeSearchShowsShowConnection.Edges, and is useful for accessing the field via an interface.
func (v *AllAnimeSearchShowsShowConnection) GetEdges() []AllAnimeSearchShowsShowConnectionEdgesShow {
	return v.Edges
}

// AllAnimeSearchShowsShowConnectionEdgesShow includes the requested fields of the GraphQL type Show.
type AllAnimeSearchShowsShowConnectionEdgesShow struct {
	Id    string `json:"_id"`
	MalId string `json:"malId"`
	Name  string `json:"name"`
}

// GetId returns AllAnimeSearchShowsShowConnectionEdgesShow.Id, and is useful for accessing the field via an interface.
func (v *AllAnimeSearchShowsShowConnectionEdgesShow) GetId() string { return v.Id }

// GetMalId returns AllAnimeSearchShowsShowConnectionEdgesShow.MalId, and is useful for accessing the field via an interface.
func (v *AllAnimeSearchShowsShowConnectionEdgesShow) GetMalId() string { return v.MalId }

// GetName returns AllAnimeSearchShowsShowConnectionEdgesShow.Name, and is useful for accessing the field via an interface.
func (v *AllAnimeSearchShowsShowConnectionEdgesShow) GetName() string { return v.Name }

// AllAnimeSeasonalShowsResponse is returned by AllAnimeSeasonalShows on success.
type AllAnimeSeasonalShowsResponse struct {
	Shows AllAnimeSeasonalShowsShowsShowConnection `json:"shows"`
}

// GetShows returns AllAnimeSeasonalShowsResponse.Shows, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsResponse) GetShows() AllAnimeSeasonalShowsShowsShowConnection {
	return v.Shows
}

// AllAnimeSeasonalShowsShowsShowConnection includes the requested fields of the GraphQL type ShowConnection.
type AllAnimeSeasonalShowsShowsShowConnection struct {
	Edges []AllAnimeSeasonalShowsShowsShowConnectionEdgesShow `json:"edges"`
}

// GetEdges returns AllAnimeSeasonalShowsShowsShowConnection.Edges, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnection) GetEdges() []AllAnimeSeasonalShowsShowsShowConnectionEdgesShow {
	return v.Edges
}

// AllAnimeSeasonalShowsShowsShowConnectionEdgesShow includes the requested fields of the GraphQL type Show.
type AllAnimeSeasonalShowsShowsShowConnectionEdgesShow struct {
	ProviderShowFields `json:"-"`
}

// GetId returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Id, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetId() string {
	return v.ProviderShowFields.Id
}

// GetName returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Name, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetName() string {
	return v.ProviderShowFields.Name
}

// GetEnglishName returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.EnglishName, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetEnglishName() string {
	return v.ProviderShowFields.EnglishName
}

// GetDescription returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Description, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetDescription() string {
	return v.ProviderShowFields.Description
}

// GetMalId returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.MalId, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetMalId() string {
	return v.ProviderShowFields.MalId
}

// GetStatus returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Status, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetStatus() string {
	return v.ProviderShowFields.Status
}

// GetThumbnail returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Thumbnail, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetThumbnail() string {
	return v.ProviderShowFields.Thumbnail
}

// GetType returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Type, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetType() string {
	return v.ProviderShowFields.Type
}

// GetSeason returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.Season, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetSeason() Object {
	return v.ProviderShowFields.Season
}

// GetEpisodeCount returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.EpisodeCount, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetEpisodeCount() string {
	return v.ProviderShowFields.EpisodeCount
}

// GetAvailableEpisodesDetail returns AllAnimeSeasonalShowsShowsShowConnectionEdgesShow.AvailableEpisodesDetail, and is useful for accessing the field via an interface.
func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) GetAvailableEpisodesDetail() Object {
	return v.ProviderShowFields.AvailableEpisodesDetail
}

func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*AllAnimeSeasonalShowsShowsShowConnectionEdgesShow
		graphql.NoUnmarshalJSON
	}
	firstPass.AllAnimeSeasonalShowsShowsShowConnectionEdgesShow = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ProviderShowFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalAllAnimeSeasonalShowsShowsShowConnectionEdgesShow struct {
	Id string `json:"_id"`

	Name string `json:"name"`

	EnglishName string `json:"englishName"`

	Description string `json:"description"`

	MalId string `json:"malId"`

	Status string `json:"status"`

	Thumbnail string `json:"thumbnail"`

	Type string `json:"type"`

	Season Object `json:"season"`

	EpisodeCount string `json:"episodeCount"`

	AvailableEpisodesDetail Object `json:"availableEpisodesDetail"`
}

func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *AllAnimeSeasonalShowsShowsShowConnectionEdgesShow) __premarshalJSON() (*__premarshalAllAnimeSeasonalShowsShowsShowConnectionEdgesShow, error) {
	var retval __premarshalAllAnimeSeasonalShowsShowsShowConnectionEdgesShow

	retval.Id = v.ProviderShowFields.Id
	retval.Name = v.ProviderShowFields.Name
	retval.EnglishName = v.ProviderShowFields.EnglishName
	retval.Description = v.ProviderShowFields.Description
	retval.MalId = v.ProviderShowFields.MalId
	retval.Status = v.ProviderShowFields.Status
	retval.Thumbnail = v.ProviderShowFields.Thumbnail
	retval.Type = v.ProviderShowFields.Type
	retval.Season = v.ProviderShowFields.Season
	retval.EpisodeCount = v.ProviderShowFields.EpisodeCount
	retval.AvailableEpisodesDetail = v.ProviderShowFields.AvailableEpisodesDetail
	return &retval, nil
}

// ProviderShowFields includes the GraphQL fields of Show requested by the fragment ProviderShowFields.
type ProviderShowFields struct {
	Id                      string `json:"_id"`
	Name                    string `json:"name"`
	EnglishName             string `json:"englishName"`
	Description             string `json:"description"`
	MalId                   string `json:"malId"`
	Status                  string `json:"status"`
	Thumbnail               string `json:"thumbnail"`
	Type                    string `json:"type"`
	Season                  Object `json:"season"`
	EpisodeCount            string `json:"episodeCount"`
	AvailableEpisodesDetail Object `json:"availableEpisodesDetail"`
}

// GetId returns ProviderShowFields.Id, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetId() string { return v.Id }

// GetName returns ProviderShowFields.Name, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetName() string { return v.Name }

// GetEnglishName returns ProviderShowFields.EnglishName, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetEnglishName() string { return v.EnglishName }

// GetDescription returns ProviderShowFields.Description, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetDescription() string { return v.Description }

// GetMalId returns ProviderShowFields.MalId, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetMalId() string { return v.MalId }

// GetStatus returns ProviderShowFields.Status, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetStatus() string { return v.Status }

// GetThumbnail returns ProviderShowFields.Thumbnail, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetThumbnail() string { return v.Thumbnail }

// GetType returns ProviderShowFields.Type, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetType() string { return v.Type }

// GetSeason returns ProviderShowFields.Season, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetSeason() Object { return v.Season }

// GetEpisodeCount returns ProviderShowFields.EpisodeCount, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetEpisodeCount() string { return v.EpisodeCount }

// GetAvailableEpisodesDetail returns ProviderShowFields.AvailableEpisodesDetail, and is useful for accessing the field via an interface.
func (v *ProviderShowFields) GetAvailableEpisodesDetail() Object { return v.AvailableEpisodesDetail }

type VaildTranslationTypeEnumType string

const (
	VaildTranslationTypeEnumTypeSub VaildTranslationTypeEnumType = "sub"
	VaildTranslationTypeEnumTypeDub VaildTranslationTypeEnumType = "dub"
	VaildTranslationTypeEnumTypeRaw VaildTranslationTypeEnumType = "raw"
)

var AllVaildTranslationTypeEnumType = []VaildTranslationTypeEnumType{
	VaildTranslationTypeEnumTypeSub,
	VaildTranslationTypeEnumTypeDub,
	VaildTranslationTypeEnumTypeRaw,
}

// __AllAnimeAvailableEpisodesInput is used internally by genqlient
type __AllAnimeAvailableEpisodesInput struct {
	ShowId string  `json:"showId"`
	Start  float64 `json:"start"`
	End    float64 `json:"end"`
}

// GetShowId returns __AllAnimeAvailableEpisodesInput.ShowId, and is useful for accessing the field via an interface.
func (v *__AllAnimeAvailableEpisodesInput) GetShowId() string { return v.ShowId }

// GetStart returns __AllAnimeAvailableEpisodesInput.Start, and is useful for accessing the field via an interface.
func (v *__AllAnimeAvailableEpisodesInput) GetStart() float64 { return v.Start }

// GetEnd returns __AllAnimeAvailableEpisodesInput.End, and is useful for accessing the field via an interface.
func (v *__AllAnimeAvailableEpisodesInput) GetEnd() float64 { return v.End }

// __AllAnimeDirectSequelsInput is used internally by genqlient
type __AllAnimeDirectSequelsInput struct {
	ShowId string `json:"showId"`
}

// GetShowId returns __AllAnimeDirectSequelsInput.ShowId, and is useful for accessing the field via an interface.
func (v *__AllAnimeDirectSequelsInput) GetShowId() string { return v.ShowId }

// __AllAnimeEpisodeSourcesInput is used internally by genqlient
type __AllAnimeEpisodeSourcesInput struct {
	ShowId          string                       `json:"showId"`
	TranslationType VaildTranslationTypeEnumType `json:"translationType"`
	EpisodeString   string                       `json:"episodeString"`
}

// GetShowId returns __AllAnimeEpisodeSourcesInput.ShowId, and is useful for accessing the field via an interface.
func (v *__AllAnimeEpisodeSourcesInput) GetShowId() string { return v.ShowId }

// GetTranslationType returns __AllAnimeEpisodeSourcesInput.TranslationType, and is useful for accessing the field via an interface.
func (v *__AllAnimeEpisodeSourcesInput) GetTranslationType() VaildTranslationTypeEnumType {
	return v.TranslationType
}

// GetEpisodeString returns __AllAnimeEpisodeSourcesInput.EpisodeString, and is useful for accessing the field via an interface.
func (v *__AllAnimeEpisodeSourcesInput) GetEpisodeString() string { return v.EpisodeString }

// __AllAnimeProviderShowInput is used internally by genqlient
type __AllAnimeProviderShowInput struct {
	ShowId string `json:"showId"`
}

// GetShowId returns __AllAnimeProviderShowInput.ShowId, and is useful for accessing the field via an interface.
func (v *__AllAnimeProviderShowInput) GetShowId() string { return v.ShowId }

// __AllAnimeSearchInput is used internally by genqlient
type __AllAnimeSearchInput struct {
	Search          SearchInput                  `json:"search"`
	TranslationType VaildTranslationTypeEnumType `json:"translationType"`
}

// GetSearch returns __AllAnimeSearchInput.Search, and is useful for accessing the field via an interface.
func (v *__AllAnimeSearchInput) GetSearch() SearchInput { return v.Search }

// GetTranslationType returns __AllAnimeSearchInput.TranslationType, and is useful for accessing the field via an interface.
func (v *__AllAnimeSearchInput) GetTranslationType() VaildTranslationTypeEnumType {
	return v.TranslationType
}

// __AllAnimeSeasonalShowsInput is used internally by genqlient
type __AllAnimeSeasonalShowsInput struct {
	Search SearchInput `json:"search"`
	Page   int         `json:"page"`
}

// GetSearch returns __AllAnimeSeasonalShowsInput.Search, and is useful for accessing the field via an interface.
func (v *__AllAnimeSeasonalShowsInput) GetSearch() SearchInput { return v.Search }

// GetPage returns __AllAnimeSeasonalShowsInput.Page, and is useful for accessing the field via an interface.
func (v *__AllAnimeSeasonalShowsInput) GetPage() int { return v.Page }

// The query executed by AllAnimeAvailableEpisodes.
const AllAnimeAvailableEpisodes_Operation = `
query AllAnimeAvailableEpisodes ($showId: String!, $start: Float!, $end: Float!) {
	show(_id: $showId) {
		availableEpisodesDetail
	}
	episodeInfos(showId: $showId, episodeNumStart: $start, episodeNumEnd: $end) {
		episodeIdNum
		notes
	}
}
`

func AllAnimeAvailableEpisodes(
	ctx_ context.Context,
	client_ graphql.Client,
	showId string,
	start float64,
	end float64,
) (data_ *AllAnimeAvailableEpisodesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AllAnimeAvailableEpisodes",
		Query:  AllAnimeAvailableEpisodes_Operation,
		Variables: &__AllAnimeAvailableEpisodesInput{
			ShowId: showId,
			Start:  start,
			End:    end,
		},
	}

	data_ = &AllAnimeAvailableEpisodesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AllAnimeDirectSequels.
const AllAnimeDirectSequels_Operation = `
query AllAnimeDirectSequels ($showId: String!) {
	show(_id: $showId) {
		relatedShows {
			relation
			showId
		}
	}
}
`

func AllAnimeDirectSequels(
	ctx_ context.Context,
	client_ graphql.Client,
	showId string,
) (data_ *AllAnimeDirectSequelsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AllAnimeDirectSequels",
		Query:  AllAnimeDirectSequels_Operation,
		Variables: &__AllAnimeDirectSequelsInput{
			ShowId: showId,
		},
	}

	data_ = &AllAnimeDirectSequelsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AllAnimeEpisodeSources.
const AllAnimeEpisodeSources_Operation = `
query AllAnimeEpisodeSources ($showId: String!, $translationType: VaildTranslationTypeEnumType!, $episodeString: String!) {
	episode(showId: $showId, translationType: $translationType, episodeString: $episodeString) {
		sourceUrls
	}
}
`

func AllAnimeEpisodeSources(
	ctx_ context.Context,
	client_ graphql.Client,
	showId string,
	translationType VaildTranslationTypeEnumType,
	episodeString string,
) (data_ *AllAnimeEpisodeSourcesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AllAnimeEpisodeSources",
		Query:  AllAnimeEpisodeSources_Operation,
		Variables: &__AllAnimeEpisodeSourcesInput{
			ShowId:          showId,
			TranslationType: translationType,
			EpisodeString:   episodeString,
		},
	}

	data_ = &AllAnimeEpisodeSourcesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AllAnimeProviderShow.
const AllAnimeProviderShow_Operation = `
query AllAnimeProviderShow ($showId: String!) {
	show(_id: $showId) {
		... ProviderShowFields
	}
}
fragment ProviderShowFields on Show {
	_id
	name
	englishName
	description
	malId
	status
	thumbnail
	type
	season
	episodeCount
	availableEpisodesDetail
}
`

func AllAnimeProviderShow(
	ctx_ context.Context,
	client_ graphql.Client,
	showId string,
) (data_ *AllAnimeProviderShowResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AllAnimeProviderShow",
		Query:  AllAnimeProviderShow_Operation,
		Variables: &__AllAnimeProviderShowInput{
			ShowId: showId,
		},
	}

	data_ = &AllAnimeProviderShowResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AllAnimeSearch.
const AllAnimeSearch_Operation = `
query AllAnimeSearch ($search: SearchInput, $translationType: VaildTranslationTypeEnumType) {
	shows(search: $search, limit: 40, page: 1, translationType: $translationType, countryOrigin: ALL) {
		edges {
			_id
			malId
			name
		}
	}
}
`

func AllAnimeSearch(
	ctx_ context.Context,
	client_ graphql.Client,
	search SearchInput,
	translationType VaildTranslationTypeEnumType,
) (data_ *AllAnimeSearchResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AllAnimeSearch",
		Query:  AllAnimeSearch_Operation,
		Variables: &__AllAnimeSearchInput{
			Search:          search,
			TranslationType: translationType,
		},
	}

	data_ = &AllAnimeSearchResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AllAnimeSeasonalShows.
const AllAnimeSeasonalShows_Operation = `
query AllAnimeSeasonalShows ($search: SearchInput, $page: Int!) {
	shows(search: $search, limit: 40, page: $page, countryOrigin: ALL) {
		edges {
			... ProviderShowFields
		}
	}
}
fragment ProviderShowFields on Show {
	_id
	name
	englishName
	description
	malId
	status
	thumbnail
	type
	season
	episodeCount
	availableEpisodesDetail
}
`

func AllAnimeSeasonalShows(
	ctx_ context.Context,
	client_ graphql.Client,
	search SearchInput,
	page int,
) (data_ *AllAnimeSeasonalShowsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AllAnimeSeasonalShows",
		Query:  AllAnimeSeasonalShows_Operation,
		Variables: &__AllAnimeSeasonalShowsInput{
			Search: search,
			Page:   page,
		},
	}

	data_ = &AllAnimeSeasonalShowsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
